version: '3'
services:
  config-server:
    image: api-infra/config-server:0.0.1-SNAPSHOT
    ports:
      - "8888:8888"
  service-discovery:
    image: api-infra/service-discovery:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    command: /scripts/wait-for-it.sh http://config-server:8888/health 30 java -jar /home/app.jar
    volumes:
      - ./wait-for-it.sh:/scripts/wait-for-it.sh:z
  apigateway:
    image: apigateway:0.0.1-SNAPSHOT
    ports:
      - "9000:9000"
    depends_on:
      - service-discovery
    command: /scripts/wait-for-it.sh http://service-discovery:8761/health 30 java -jar /home/app.jar
    volumes:
      - ./wait-for-it.sh:/scripts/wait-for-it.sh:z
  api-svca-service:
    image: api-svca-service:0.0.1-SNAPSHOT
    depends_on:
      - service-discovery
    command: /scripts/wait-for-it.sh http://service-discovery:8761/health 30 java -jar /home/app.jar
    volumes:
      - ./wait-for-it.sh:/scripts/wait-for-it.sh:z
  api-svcb-service:
    image: api-svcb-service:0.0.1-SNAPSHOT
    depends_on:
      - service-discovery
    command: /scripts/wait-for-it.sh http://service-discovery:8761/health 30 java -jar /home/app.jar
    volumes:
      - ./wait-for-it.sh:/scripts/wait-for-it.sh:z
  turbine-hystrix-dashboard:
    image: api-infra/turbine-hystrix-dashboard:0.0.1-SNAPSHOT
    ports:
      - 8010:8010
    command: /scripts/wait-for-it.sh http://service-discovery:8761/health 30 java -jar /home/app.jar
    volumes:
      - ./wait-for-it.sh:/scripts/wait-for-it.sh:z